########################
# ACME Config          #
########################

########################
# SPRING Config        #
########################
# Logging
logging:
  level:
    org.springframework: INFO
    com.acme: DEBUG

# Spring
spring:
  # Application
  application:
    name: acme-loan-validation
  # Jackson
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  # Kafka
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      group-id: ${spring.application.name}-group
    listener:
      concurrency: 1
#      poll-timeout: 3000ms

# Management
management:
  server:
    servlet:
      context-path: /api/management
  endpoint:
    health: # None sensitive, Shows application health information
      enabled: true
    info: # None sensitive, Displays arbitrary application info.
      enabled: true
    env: # Sensitive, Exposes properties from Spring’s ConfigurableEnvironment.
      enabled: true
    beans: # Sensitive, Displays a complete list of all the Spring beans in your application.
      enabled: true
    configprops: # Sensitive, Displays a collated list of all @ConfigurationProperties.
      enabled: true
    metrics: # Sensitive, Shows ‘metrics’ information for the current application.
      enabled: true
    httptrace: # Sensitive, Displays trace information (by default the last 100 HTTP requests).
      enabled: true
    loggers: # Sensitive, Shows and modifies the configuration of loggers in the application.
      enabled: true
    flyway: # Sensitive, Shows any Flyway database migrations that have been applied.
      enabled: true
